/// SOA interface methods definition to circumvent FPC restriction
// - generated at 2015-01-16 16:41:13
unit TestSQL3FPCInterfaces;

{
  WARNING:
    This unit has been generated by a mORMot 1.18.721 server.
    Any manual modification of this file may be lost after regeneration.

  Synopse mORMot framework. Copyright (C) 2015 Arnaud Bouchez
    Synopse Informatique - http://synopse.info

  This unit is released under a MPL/GPL/LGPL tri-license,
  and therefore may be freely included in any application.

  This unit is intended to work on FPC compilers, which lacks of RTTI
  for interfaces - see http://bugs.freepascal.org/view.php?id=26774
  
  USAGE:

  Add this TestSQL3FPCInterfaces unit to your uses clause, so that the following
  interfaces would be defined as expected by mORMot under FPC:

   - ICalculator
   - IComplexCalculator
   - IComplexNumber
   - ITestSession
   - ITestUser
   - ITestGroup
   - ITestPerThread
   - ISmsSender
   - IUserRepository
  
}

interface

{$I Synopse.inc} // needed for setting proper FPC modes

uses
  SysUtils,
  Classes,
  SynCommons,
  mORMot,
  SynSelfTests;


implementation

{$ifdef FPC} // circumvent a FPC-only bug: Delphi has RTTI for this

{ TInterfaceFactoryDefinition }

type
  /// define and manage missing interface RTTI for defined interfaces
  TInterfaceFactoryDefinition = class(TInterfaceFactoryGenerated)
  protected
    /// will declare the following types to the interface factory:
    // - ICalculator
    // - IComplexCalculator
    // - IComplexNumber
    // - ITestSession
    // - ITestUser
    // - ITestGroup
    // - ITestPerThread
    // - ISmsSender
    // - IUserRepository
    procedure AddMethodsFromTypeInfo(aInterface: PTypeInfo); override;
  end;

procedure TInterfaceFactoryDefinition.AddMethodsFromTypeInfo(aInterface: PTypeInfo);
begin
  if aInterface=TypeInfo(ICalculator) then begin
    AddMethod('Add',[
      ord(smdconst),'n1',TypeInfo(Integer),
      ord(smdconst),'n2',TypeInfo(Integer),
      ord(smdresult),'Result',TypeInfo(Integer)]);
    AddMethod('Multiply',[
      ord(smdconst),'n1',TypeInfo(Int64),
      ord(smdconst),'n2',TypeInfo(Int64),
      ord(smdresult),'Result',TypeInfo(Int64)]);
    AddMethod('Subtract',[
      ord(smdconst),'n1',TypeInfo(Double),
      ord(smdconst),'n2',TypeInfo(Double),
      ord(smdresult),'Result',TypeInfo(Double)]);
    AddMethod('ToText',[
      ord(smdconst),'Value',TypeInfo(Currency),
      ord(smdvar),'Result',TypeInfo(RawUTF8)]);
    AddMethod('ToTextFunc',[
      ord(smdconst),'Value',TypeInfo(Double),
      ord(smdresult),'Result',TypeInfo(String)]);
    AddMethod('SpecialCall',[
      ord(smdconst),'Txt',TypeInfo(RawUTF8),
      ord(smdvar),'Int',TypeInfo(Integer),
      ord(smdvar),'Card',TypeInfo(Cardinal),
      ord(smdconst),'field',TypeInfo(TSynTableFieldTypes),
      ord(smdconst),'fields',TypeInfo(TSynTableFieldTypes),
      ord(smdvar),'options',TypeInfo(TSynTableFieldOptions),
      ord(smdresult),'Result',TypeInfo(TSynTableFieldTypes)]);
    AddMethod('ComplexCall',[
      ord(smdconst),'Ints',TypeInfo(TIntegerDynArray),
      ord(smdconst),'Strs1',TypeInfo(TRawUTF8DynArray),
      ord(smdvar),'Str2',TypeInfo(TWideStringDynArray),
      ord(smdconst),'Rec1',TypeInfo(TVirtualTableModuleProperties),
      ord(smdvar),'Rec2',TypeInfo(TSQLRestCacheEntryValue),
      ord(smdconst),'Float1',TypeInfo(Double),
      ord(smdvar),'Float2',TypeInfo(Double),
      ord(smdresult),'Result',TypeInfo(TSQLRestCacheEntryValue)]);
    exit;
  end;
  if aInterface=TypeInfo(IComplexCalculator) then begin
    AddMethod('Add',[
      ord(smdconst),'n1',TypeInfo(Integer),
      ord(smdconst),'n2',TypeInfo(Integer),
      ord(smdresult),'Result',TypeInfo(Integer)]);
    AddMethod('Multiply',[
      ord(smdconst),'n1',TypeInfo(Int64),
      ord(smdconst),'n2',TypeInfo(Int64),
      ord(smdresult),'Result',TypeInfo(Int64)]);
    AddMethod('Subtract',[
      ord(smdconst),'n1',TypeInfo(Double),
      ord(smdconst),'n2',TypeInfo(Double),
      ord(smdresult),'Result',TypeInfo(Double)]);
    AddMethod('ToText',[
      ord(smdconst),'Value',TypeInfo(Currency),
      ord(smdvar),'Result',TypeInfo(RawUTF8)]);
    AddMethod('ToTextFunc',[
      ord(smdconst),'Value',TypeInfo(Double),
      ord(smdresult),'Result',TypeInfo(String)]);
    AddMethod('SpecialCall',[
      ord(smdconst),'Txt',TypeInfo(RawUTF8),
      ord(smdvar),'Int',TypeInfo(Integer),
      ord(smdvar),'Card',TypeInfo(Cardinal),
      ord(smdconst),'field',TypeInfo(TSynTableFieldTypes),
      ord(smdconst),'fields',TypeInfo(TSynTableFieldTypes),
      ord(smdvar),'options',TypeInfo(TSynTableFieldOptions),
      ord(smdresult),'Result',TypeInfo(TSynTableFieldTypes)]);
    AddMethod('ComplexCall',[
      ord(smdconst),'Ints',TypeInfo(TIntegerDynArray),
      ord(smdconst),'Strs1',TypeInfo(TRawUTF8DynArray),
      ord(smdvar),'Str2',TypeInfo(TWideStringDynArray),
      ord(smdconst),'Rec1',TypeInfo(TVirtualTableModuleProperties),
      ord(smdvar),'Rec2',TypeInfo(TSQLRestCacheEntryValue),
      ord(smdconst),'Float1',TypeInfo(Double),
      ord(smdvar),'Float2',TypeInfo(Double),
      ord(smdresult),'Result',TypeInfo(TSQLRestCacheEntryValue)]);
    AddMethod('Substract',[
      ord(smdconst),'n1',TypeInfo(TComplexNumber),
      ord(smdconst),'n2',TypeInfo(TComplexNumber),
      ord(smdout),'Result',TypeInfo(TComplexNumber)]);
    AddMethod('IsNull',[
      ord(smdconst),'n',TypeInfo(TComplexNumber),
      ord(smdresult),'Result',TypeInfo(Boolean)]);
    AddMethod('TestBlob',[
      ord(smdconst),'n',TypeInfo(TComplexNumber),
      ord(smdresult),'Result',TypeInfo(TServiceCustomAnswer)]);
    AddMethod('TestVariants',[
      ord(smdconst),'Text',TypeInfo(RawUTF8),
      ord(smdconst),'V1',TypeInfo(Variant),
      ord(smdvar),'V2',TypeInfo(Variant),
      ord(smdresult),'Result',TypeInfo(Variant)]);
    AddMethod('Collections',[
      ord(smdconst),'Item',TypeInfo(TCollTest),
      ord(smdvar),'List',TypeInfo(TCollTestsI),
      ord(smdout),'Copy',TypeInfo(TCollTestsI)]);
    AddMethod('GetCurrentThreadID',[
      ord(smdresult),'Result',TypeInfo(Cardinal)]);
    AddMethod('GetCustomer',[
      ord(smdconst),'CustomerId',TypeInfo(Integer),
      ord(smdout),'CustomerData',TypeInfo(TCustomerData),
      ord(smdresult),'Result',TypeInfo(Boolean)]);
    AddMethod('FillPeople',[
      ord(smdvar),'People',TypeInfo(TSQLRecordPeople)]);
    exit;
  end;
  if aInterface=TypeInfo(IComplexNumber) then begin
    AddMethod('Assign',[
      ord(smdconst),'aReal',TypeInfo(Double),
      ord(smdconst),'aImaginary',TypeInfo(Double)]);
    AddMethod('GetImaginary',[
      ord(smdresult),'Result',TypeInfo(Double)]);
    AddMethod('GetReal',[
      ord(smdresult),'Result',TypeInfo(Double)]);
    AddMethod('SetImaginary',[
      ord(smdconst),'Value',TypeInfo(Double)]);
    AddMethod('SetReal',[
      ord(smdconst),'Value',TypeInfo(Double)]);
    AddMethod('Add',[
      ord(smdconst),'aReal',TypeInfo(Double),
      ord(smdconst),'aImaginary',TypeInfo(Double)]);
    exit;
  end;
  if aInterface=TypeInfo(ITestSession) then begin
    AddMethod('GetContextSessionID',[
      ord(smdresult),'Result',TypeInfo(Integer)]);
    AddMethod('GetContextSessionUser',[
      ord(smdresult),'Result',TypeInfo(Integer)]);
    AddMethod('GetContextSessionGroup',[
      ord(smdresult),'Result',TypeInfo(Integer)]);
    exit;
  end;
  if aInterface=TypeInfo(ITestUser) then begin
    AddMethod('GetContextSessionID',[
      ord(smdresult),'Result',TypeInfo(Integer)]);
    AddMethod('GetContextSessionUser',[
      ord(smdresult),'Result',TypeInfo(Integer)]);
    AddMethod('GetContextSessionGroup',[
      ord(smdresult),'Result',TypeInfo(Integer)]);
    exit;
  end;
  if aInterface=TypeInfo(ITestGroup) then begin
    AddMethod('GetContextSessionID',[
      ord(smdresult),'Result',TypeInfo(Integer)]);
    AddMethod('GetContextSessionUser',[
      ord(smdresult),'Result',TypeInfo(Integer)]);
    AddMethod('GetContextSessionGroup',[
      ord(smdresult),'Result',TypeInfo(Integer)]);
    exit;
  end;
  if aInterface=TypeInfo(ITestPerThread) then begin
    AddMethod('GetContextServiceInstanceID',[
      ord(smdresult),'Result',TypeInfo(Cardinal)]);
    AddMethod('GetThreadIDAtCreation',[
      ord(smdresult),'Result',TypeInfo(Cardinal)]);
    AddMethod('GetCurrentThreadID',[
      ord(smdresult),'Result',TypeInfo(Cardinal)]);
    AddMethod('GetCurrentRunningThreadID',[
      ord(smdresult),'Result',TypeInfo(Cardinal)]);
    exit;
  end;
  if aInterface=TypeInfo(ISmsSender) then begin
    AddMethod('Send',[
      ord(smdconst),'Text',TypeInfo(RawUTF8),
      ord(smdconst),'Number',TypeInfo(RawUTF8),
      ord(smdresult),'Result',TypeInfo(Boolean)]);
    exit;
  end;
  if aInterface=TypeInfo(IUserRepository) then begin
    AddMethod('GetUserByName',[
      ord(smdconst),'Name',TypeInfo(RawUTF8),
      ord(smdresult),'Result',TypeInfo(TUser)]);
    AddMethod('Save',[
      ord(smdconst),'User',TypeInfo(TUser)]);
    exit;
  end;
end;

initialization
  TInterfaceFactoryDefinition.RegisterInterface(TypeInfo(ICalculator));
  TInterfaceFactoryDefinition.RegisterInterface(TypeInfo(IComplexCalculator));
  TInterfaceFactoryDefinition.RegisterInterface(TypeInfo(IComplexNumber));
  TInterfaceFactoryDefinition.RegisterInterface(TypeInfo(ITestSession));
  TInterfaceFactoryDefinition.RegisterInterface(TypeInfo(ITestUser));
  TInterfaceFactoryDefinition.RegisterInterface(TypeInfo(ITestGroup));
  TInterfaceFactoryDefinition.RegisterInterface(TypeInfo(ITestPerThread));
  TInterfaceFactoryDefinition.RegisterInterface(TypeInfo(ISmsSender));
  TInterfaceFactoryDefinition.RegisterInterface(TypeInfo(IUserRepository));

{$endif FPC}
end.